defaults: &defaults
  adapter: mysql2
  username: root
  password: 
  host: localhost

development:
  database: atlas_dev
  uri: mysql://localhost/atlas_dev?user=root
  <<: *defaults

test:
  database: atlas_test
  uri: mysql://localhost/atlas_test?user=root
  <<: *defaults
production:
  database: atlas_pro
  <<: *defaults
